export const productSections = [
  {
    key: "all",
    title: "All Organic Products",
    subtitle: "Browse our complete range of natural Himalayan foods from Uttarakhand.",
    seoTitle: "Organic Products from Uttarakhand | GharKaOrganic",
    seoDescription: "Shop all organic pahadi products — pickles, ghee, honey, spices and more. Natural, chemical-free, delivered across India.",
    seoKeywords: "organic food india, pahadi products online, uttarakhand natural food",
    badge: null,
    bannerDesktop: "/banners/gharka-pickle-1500x500.webp",
    bannerMobile: "/banners/gharka-pickle-1500x500.webp",
    chipImage: "/icons/categories/all.png", // 80x80px webp
  },

  {
    key: "new",
    title: "Most Loved Products",
    subtitle: "Best-selling natural, chemical-free products trusted by families across India.",
    seoTitle: "Best Organic Products in India | Most Loved Natural Food",
    seoDescription: "Shop most loved organic food products from Uttarakhand including pahadi achar, desi ghee, raw honey and natural homemade foods.",
    seoKeywords: "organic products india, natural food india, best selling organic food",
    badge: "Bestsellers",
    bannerDesktop: "/banners/bestsellers-1500x500.webp",
    bannerMobile: "/banners/bestsellers-mobile.webp",
    chipImage: "/icons/categories/bestseller.png",
  },
  {
    key: "honey",
    title: "Pure Pahadi Honey",
    subtitle: "Raw forest honey collected from Himalayan flowers, unprocessed and chemical-free.",
    seoTitle: "Buy Raw Honey Online from Uttarakhand | Pure Forest Honey India",
    seoDescription: "Order pure raw honey from Uttarakhand forests. Natural, unprocessed, and rich in nutrients. Delivered across India.",
    seoKeywords: "raw honey uttarakhand, forest honey india, natural honey online",
    badge: "Pure & Raw",
    bannerDesktop: "/banners/honey-1500x500.webp",
    bannerMobile: "/banners/honey-mobile.webp",
    chipImage: "/icons/categories/honey.png",
  },
  {
    key: "ghee",
    title: "Pure Desi Cow Ghee",
    subtitle: "Traditional A2 cow ghee made using bilona method for authentic taste and nutrition.",
    seoTitle: "Buy Desi Ghee Online | A2 Cow Ghee India | Pure Bilona Ghee",
    seoDescription: "Shop pure desi cow ghee made using traditional bilona method. 100% natural, chemical-free and rich in aroma.",
    seoKeywords: "desi ghee online, a2 ghee india, bilona ghee uttarakhand",
    badge: "Bilona Method",
    bannerDesktop: "/banners/ghee-1500x500.webp",
    bannerMobile: "/banners/ghee-mobile.webp",
    chipImage: "/icons/categories/ghee.png",
  },
  {
    key: "pickle",
    title: "Homemade Pahadi Pickles",
    subtitle: "Traditional Kumaoni pickle,,s made using authentic recipes without preservatives.",
    seoTitle: "Buy Pahadi Achar Online | Homemade Pickles India",
    seoDescription: "Order homemade pahadi pickles from Uttarakhand. Traditional taste, no preservatives, fully natural ingredients.",
    seoKeywords: "pahadi achar online, homemade pickle india, uttarakhand achar",
    badge: "No Preservatives",
    bannerDesktop: "/picle.jpeg",
    bannerMobile: "/gharka-mango-1200x400.jpeg",
    chipImage: "/icons/categories/pickle.png",
  },
  {
    key: "spices",
    title: "Fresh Pahadi Spices",
    subtitle: "Aromatic hand-ground spices from Uttarakhand for authentic Indian cooking.",
    seoTitle: "Buy Pahadi Spices Online | Natural Indian Masalas",
    seoDescription: "Shop fresh pahadi spices and masalas from Uttarakhand. Naturally sourced and stone-ground for authentic taste.",
    seoKeywords: "pahadi spices, indian masala online, natural spices india",
    badge: "Stone Ground",
    bannerDesktop: "/banners/spices-1500x500.webp",
    bannerMobile: "/banners/spices-mobile.webp",
    chipImage: "/icons/categories/spices.png",
  },
  {
    key: "pahadiSalts",
    title: "Pahadi Herbal Salts",
    subtitle: "Unique Himalayan salts infused with natural herbs and traditional minerals.",
    seoTitle: "Buy Herbal Salt Online | Himalayan Pahadi Salt India",
    seoDescription: "Explore Himalayan herbal salts infused with natural minerals and traditional flavors from Uttarakhand.",
    seoKeywords: "himalayan salt india, herbal salt online, pahadi salt",
    badge: "Himalayan",
    bannerDesktop: "/banners/salts-1500x500.webp",
    bannerMobile: "/banners/salts-mobile.webp",
    chipImage: "/icons/categories/salt.png",
  },
  {
    key: "pahadiDals",
    title: "Organic Pahadi Dals",
    subtitle: "Nutritious and naturally grown pulses from Himalayan farms.",
    seoTitle: "Buy Organic Dal Online | Pahadi Pulses from Uttarakhand",
    seoDescription: "Shop organic pahadi dals and pulses grown in Uttarakhand hills. Healthy, chemical-free and rich in nutrition.",
    seoKeywords: "organic dal india, pahadi pulses, natural dal uttarakhand",
    badge: "Chemical-Free",
    bannerDesktop: "/banners/dals-1500x500.webp",
    bannerMobile: "/banners/dals-mobile.webp",
    chipImage: "/icons/categories/dal.png",
  },
   {
    key: "chutney",
    title: "Instant Chutney",
    subtitle: "Browse our complete range of natural Himalayan foods from Uttarakhand.",
    seoTitle: "Organic Products from Uttarakhand | GharKaOrganic",
    seoDescription: "Shop all organic pahadi products — pickles, ghee, honey, spices and more. Natural, chemical-free, delivered across India.",
    seoKeywords: "organic food india, pahadi products online, uttarakhand natural food",
    badge: null,
    bannerDesktop: "/banners/gharka-pickle-1500x500.webp",
    bannerMobile: "/banners/gharka-pickle-1500x500.webp",
    chipImage: "/icons/categories/chutney.png", // 80x80px webp
  },
];